apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: node-js
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: tusharacr.azurecr.io/nodejs-app:b8e4539148a8225b715d15953908595e1507ee45
        ports:
        - containerPort: 8080
      # Add this block to authenticate using the secret you just created
      imagePullSecrets:
      - name: acr-auth
